<?php
/** @var \FlexShopper\Payments\Block\Adminhtml\Info $block */
$flexShopperId = $block->getFlexshopperId();
$flexShopperTxid = $block->getFlexshopperTxid();
?>

<?php if ($flexShopperId): ?>
<?= __('Flexshopper Lease ID:') ?> <?= $flexShopperId ?><br/>
<?= __('Transaction ID:') ?> <?= $flexShopperTxid ?><br/>
<?= __('In order to receive payment, please provide shipping details.') ?>
<?php endif ?>
